### ISSUE TITLE
How to use Firebase Auth in Razor Component

### ISSUE THREAD

**Issue by BenHayat** [AnkitSharma-007/Blazor-CRUD-With-CloudFirestore#1]
Could you please create an article how to create user and authenticate user in FB Auth using Razor Components (in C# than js) and able to get token back from FB and allow the Razor server side to verify that token.

**Comment by AnkitSharma-007** [comment]
Blazor has recently added the feature for authentication. Check this article for FB auth in a Blazor app.
https://ankitsharmablogs.com/facebook-authentication-and-authorization-in-server-side-blazor-app/
